export const UPDATE_POSTS = "UPDATE_POSTS";

// Login action Types
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//SignUp Action Types
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

/* PERSISTING THE USER */
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const LOG_OUT = "LOG_OUT";

/* CLEARING AUTH STATE WHILE NAVIGATING TO ANOTHER PAGE */
export const CLEAR_AUTH_STATE = "CLEAR_AUTH_STATE";

/* FOR UPDATING THE CREDENTIALS */
export const EDIT_USER_SUCCESSFUL = "EDIT_USER_SUCCESSFUL";
export const EDIT_USER_FAILED = "EDIT_USER_FAILED";
