export const UPDATE_POSTS = "UPDATE_POSTS";

// Login action Types
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//SignUp Action Types
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

/* PERSISTING THE USER */
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const LOG_OUT = "LOG_OUT";

/* CLEARING AUTH STATE WHILE NAVIGATING TO ANOTHER PAGE */
export const CLEAR_AUTH_STATE = "CLEAR_AUTH_STATE";

/* FOR UPDATING THE CREDENTIALS */
export const EDIT_USER_IN_PROGRESS = "EDIT_USER_IN_PROGRESS";
export const EDIT_USER_SUCCESSFUL = "EDIT_USER_SUCCESSFUL";
export const EDIT_USER_FAILED = "EDIT_USER_FAILED";

/* USER'S PROFILE */
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";
export const FETCH_USER_PROFILE_START = "FETCH_USER_PROFILE_START";

/* FRIEND LIST */
export const FETCH_FRIENDS_SUCCCESS='FETCH_FRIENDS_SUCCCESS';
export const FETCH_FRIENDS_START='FETCH_FRIENDS_START';
export const FETCH_FRIENDS_FAILURE='FETCH_FRIENDS_FAILURE';

/* ADD FRIEND */
export const ADD_FRIEND='ADD_FRIEND';